# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmscategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='page',
            name='categories',
        ),
        migrations.DeleteModel(
            name='CMSCategory',
        ),
    ]
